# 測試環境的數據庫配置
server:
  port: 8002

# 前端訪問地址（用於後端登錄完成後 redirect 回前端，dev 必須帶 port）
sp:
  frontend:
    url: http://10.32.96.55:8082

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主庫數據源
      master:
        url: jdbc:mysql://10.32.96.45:3306/school_student_management_test?useSSL=false&serverTimezone=Asia/Taipei&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&initialTimeout=2&connectTimeout=60000&socketTimeout=60000
        username: dba_user
        password: StrongP@ssw0rd
        # 初始連接數
        initialSize: 3
        # 最小連接池數量
        minIdle: 3
        # 最大連接池數量
        maxActive: 8
        # 配置獲取連接等待超時的時間
        maxWait: 60000
        # 配置連接超時時間
        connectTimeout: 30000
        # 配置網絡超時時間
        socketTimeout: 60000
        # 配置間隔多久才進行一次檢測，檢測需要關閉的空閒連接，單位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一個連接在池中最小生存的時間，單位是毫秒
        minEvictableIdleTimeMillis: 300000
        # 配置一個連接在池中最大生存的時間，單位是毫秒
        maxEvictableIdleTimeMillis: 1800000
        # 配置檢測連接是否有效
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false
        # 啓用異常時移除連接
        removeAbandoned: true
        removeAbandonedTimeout: 180
        logAbandoned: true
        # MySQL特定配置
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 啓用ping檢查
        keepAlive: true
      # 從庫數據源
      slave:
        # 從數據源開關/默認關閉
        enabled: false
        url: 
        username: 
        password: 
      webStatFilter: 
        enabled: false
      statViewServlet:
        enabled: false
        # 設置白名單，不填則允許所有訪問
        allow:
        url-pattern: /druid/*
        # 控制臺管理用戶名和密碼
        login-username: sp
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL記錄
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

# 企業微信配置
wechat:
  work:
    corpId: ww04fad852e91fd490
    agentId: 1000033
    secret: I31-B5clKayPf4vNl2bibhL1ia8x4cwIc884xK888Fc
    redirectUri: https://mo-stu-sys.org-assistant.com/sp-api/wechat/oauth/callback
    # 回調配置
    callback:
      token: YWhmCsbcN5dtvkN44t5aywaOxcxDWWMO
      encodingAesKey: 4C7hzSn2qFrO1hzMIJBY5iTL7UPKFZSUwmMX9TLF80D
      corpId: wpV9pWDAAA1nyVENSNCp5_m185fWSXEg
      permanentCode: I31-B5clKayPf4vNl2bibhL1ia8x4cwIc884xK888Fc